# Generated by Django 2.2.12 on 2024-07-10 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_name', models.CharField(max_length=20)),
                ('factory_email', models.EmailField(max_length=254)),
                ('factory_location', models.CharField(max_length=20)),
                ('factory_reg_no', models.CharField(max_length=20)),
                ('farmer_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farmers_details.Farmers_details')),
            ],
        ),
    ]
