# Generated by Django 4.2.14 on 2024-07-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_details', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factory_details',
            old_name='farmer_id',
            new_name='farmers_id',
        ),
        migrations.AlterField(
            model_name='factory_details',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
