# Generated by Django 4.2.13 on 2024-07-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.SmallIntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('id_number', models.CharField(max_length=15)),
                ('phone_number', models.PositiveSmallIntegerField()),
                ('payment_due', models.PositiveBigIntegerField()),
                ('input', models.PositiveIntegerField()),
            ],
        ),
    ]
