# Generated by Django 2.2.12 on 2024-07-10 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmers_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmers_id', models.IntegerField(default=1)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('id_number', models.CharField(max_length=15)),
                ('phone_number', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
